# Generated by Django 3.2.7 on 2022-06-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertyviews',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
